import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import Navigation from "./Navigation/navigation";
import Footer from "./Footer/page";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
       <div className="w-full h-full flex flex-col  bg-[#05203c] overflow-hidden overflow-x-hidden">
       <div className=" bg-[#05203c] flex items-center justify-center  w-full"> <Navigation/></div> 
        {children}
       <Footer/>
      </div>
    </html>
  );
}
