import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import Navigation from "./Navigation/navigation";
import Footer from "./Footer/page";
import { DataProvider } from "./ContextApi/ContextApi";



const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
       <head>
            <link rel="stylesheet" href="https://unpkg.com/leaflet@1.9.4/dist/leaflet.css"  integrity="sha256-p4NxAoJBhIIN+hmNHrzRCf9tD/miZyoHS5obTRR9BMY=" />
             <script src="https://unpkg.com/leaflet@1.9.4/dist/leaflet.js" integrity="sha256-20nQCchB9co0qIjJZRGuk2/Z9VM+kNiyxNV1lvTlZBo="></script>
       </head>
       <body className="w-full h-full flex flex-col  bg-[#05203c] overflow-hidden overflow-x-hidden overflow-y-scroll">
              <div className=" bg-[#05203c] flex items-center justify-center  w-full"> <Navigation/></div> 
          <DataProvider>
              {children}
              <Footer/>
          </DataProvider>
      </body>
 
      </html>
  );
}
